## import

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

#Create Gold Dataset

## load related only dataset

In [ ]:
path = '/content/drive/MyDrive/yourpath'

In [ ]:
related_only_path = '/content/drive/MyDrive/yourpath/mapping related only Q&QA.xlsx'

In [ ]:
QA_related_only_dataset = pd.read_excel(related_only_path, sheet_name="QA related only")
Q_related_only_dataset = pd.read_excel(related_only_path, sheet_name="Q related only")

In [ ]:
Q_related_only_dataset.columns

Index(['Column1', 'id1', 'sentence1', 'tahun1', 'id_x', 'input_x', 'id2',
       'sentence2', 'tahun2', 'id_y', 'input_y', 'relationship', 'input_x_v2',
       'input_y_v2', 'penjelasan'],
      dtype='object')

In [ ]:
QA_related_only_dataset.columns

Index(['Column1', 'year', 'variable', 'id', 'blok', 'label', 'pertanyaan',
       'jawaban', 'input_x', 'year2', 'variable2', 'id2', 'blok2', 'label2',
       'pertanyaan2', 'jawaban2', 'input_y', 'relationship', 'penjelasan'],
      dtype='object')

In [ ]:
Q_equivalent_df = Q_related_only_dataset[['id1','tahun1','input_x_v2','id2','tahun2','input_y_v2','relationship','penjelasan']][Q_related_only_dataset['relationship']=='equivalent']
Q_aggregated_df = Q_related_only_dataset[['id1','tahun1','input_x_v2','id2','tahun2','input_y_v2','relationship','penjelasan']][Q_related_only_dataset['relationship']=='lebih umum dari']
Q_detailed_df = Q_related_only_dataset[['id1','tahun1','input_x_v2','id2','tahun2','input_y_v2','relationship','penjelasan']][Q_related_only_dataset['relationship']=='lebih khusus dari']

In [ ]:
QA_equivalent_df = QA_related_only_dataset[['id','year','input_x','id2','year2','input_y','relationship','penjelasan']][QA_related_only_dataset['relationship']=='equivalent']
QA_aggregated_df = QA_related_only_dataset[['id','year','input_x','id2','year2','input_y','relationship','penjelasan']][QA_related_only_dataset['relationship']=='lebih umum dari']
QA_detailed_df = QA_related_only_dataset[['id','year','input_x','id2','year2','input_y','relationship','penjelasan']][QA_related_only_dataset['relationship']=='lebih khusus dari']

In [ ]:
print(Q_related_only_dataset.shape)

print("\n")
print(Q_equivalent_df.shape)
print(Q_aggregated_df.shape)
print(Q_detailed_df.shape)

print("\n\n")

print(QA_related_only_dataset.shape)
print("\n")
print(QA_equivalent_df.shape)
print(QA_aggregated_df.shape)
print(QA_detailed_df.shape)

(630, 15)


(563, 8)
(63, 8)
(4, 8)



(1730, 19)


(1349, 8)
(111, 8)
(270, 8)

##create unrelated dataset

In [ ]:
Q_input_x_list = Q_related_only_dataset[['id1','tahun1','input_x_v2']].drop_duplicates().values.tolist()
Q_input_y_list = Q_related_only_dataset[['id2','tahun2','input_y_v2']].drop_duplicates().values.tolist()

QA_input_x_list = QA_related_only_dataset[['id','year','input_x']].drop_duplicates().values.tolist()
QA_input_y_list = QA_related_only_dataset[['id2','year2','input_y']].drop_duplicates().values.tolist()

In [ ]:
print((len(Q_input_x_list) , len(Q_input_y_list)),len(Q_related_only_dataset))
print((len(Q_input_x_list) * len(Q_input_y_list))-len(Q_related_only_dataset))

(272, 280) 630
75530

In [ ]:
Q_related_pairs_set = set()
for index, row in Q_related_only_dataset.iterrows():
    Q_related_pairs_set.add((row['id1'], row['tahun1'], row['input_x_v2'], row['id2'], row['tahun2'], row['input_y_v2']))

print(f"Created Q_related_pairs_set with {len(Q_related_pairs_set)} unique pairs.")

Created Q_related_pairs_set with 630 unique pairs.

In [ ]:
Q_unrelated_data_all = []
for id1, tahun1, input_x_v2 in Q_input_x_list:
    for id2, tahun2, input_y_v2 in Q_input_y_list:
        if (id1, tahun1, input_x_v2, id2, tahun2, input_y_v2) not in Q_related_pairs_set and tahun1<tahun2:
            Q_unrelated_data_all.append({
                'id1': id1,
                'tahun1': tahun1,
                'input_x_v2': input_x_v2,
                'id2': id2,
                'tahun2': tahun2,
                'input_y_v2': input_y_v2,
                'relationship': 'tidak ada hubungan',
                'penjelasan' : 'kedua pertanyaan tersebut tidak berkaitan atau berhubungan'
            })

Q_unrelated_df_all = pd.DataFrame(Q_unrelated_data_all)
print(f"Created Q_unrelated_df with {len(Q_unrelated_df_all)} unrelated pairs.")

Created Q_unrelated_df with 48116 unrelated pairs.

In [ ]:
print((len(QA_input_x_list) , len(QA_input_y_list)),len(QA_related_only_dataset))
print((len(QA_input_x_list) * len(QA_input_y_list)))
print((len(QA_input_x_list) * len(QA_input_y_list))-len(QA_related_only_dataset))

(1001, 907) 1730
907907
906177

In [ ]:
QA_related_pairs_set = set()
for index, row in QA_related_only_dataset.iterrows():
    QA_related_pairs_set.add((row['id'], row['year'], row['input_x'], row['id2'], row['year2'], row['input_y']))
print(f"Created QA_related_pairs_set with {len(QA_related_pairs_set)} unique pairs.")

Created QA_related_pairs_set with 1730 unique pairs.

In [ ]:
QA_unrelated_data_all = []

for id, year, input_x in QA_input_x_list:
  for id2, year2, input_y in QA_input_y_list:
    if (id, year, input_x, id2, year2, input_y) not in QA_related_pairs_set and year<year2:

      QA_unrelated_data_all.append({
          'id': id,
          'year': year,
          'input_x': input_x,
          'id2': id2,
          'year2': year2,
          'input_y': input_y,
          'relationship': 'tidak ada hubungan',
          'penjelasan' : 'kedua kategori tersebut tidak berkaitan atau berhubungan'
      })

QA_unrelated_df_all = pd.DataFrame(QA_unrelated_data_all)
print(f"Created QA_unrelated_df with {len(QA_unrelated_df_all)} unrelated pairs.")

Created QA_unrelated_df with 599745 unrelated pairs.

## create all pair dataset without reverse

In [ ]:
# Q_related_only_dataset.to_csv(path+'/00_Q_related_only_dataset(2).csv', index=False)
# Q_equivalent_df.to_csv(path+'/00_Q_equivalent_df(2).csv', index=False)
# Q_aggregated_df.to_csv(path+'/00_Q_aggregated_df(2).csv', index=False)
# Q_detailed_df.to_csv(path+'/00_Q_detailed_df(2).csv', index=False)
Q_unrelated_df_all.to_csv(path+'/00_Q_unrelated_df_all(2a).csv', index=False)


# QA_related_only_dataset.to_csv(path+'/00_QA_related_only_dataset(2).csv', index=False)
# QA_equivalent_df.to_csv(path+'/00_QA_equivalent_df(2).csv', index=False)
# QA_aggregated_df.to_csv(path+'/00_QA_aggregated_df(2).csv', index=False)
# QA_detailed_df.to_csv(path+'/00_QA_detailed_df(2).csv', index=False)
QA_unrelated_df_all.to_csv(path+'/00_QA_unrelated_df_all(2a).csv', index=False)

Q_all_dataset = pd.concat([Q_related_only_dataset[['id1', 'tahun1', 'input_x_v2', 'id2', 'tahun2', 'input_y_v2','relationship', 'penjelasan']], Q_unrelated_df_all])
QA_all_dataset = pd.concat([QA_related_only_dataset[['id', 'year', 'input_x', 'id2', 'year2', 'input_y', 'relationship','penjelasan']], QA_unrelated_df_all])

Q_all_dataset.to_csv(path+'/00_Q_all_dataset(2a).csv', index=False)
QA_all_dataset.to_csv(path+'/00_QA_all_dataset(2a).csv', index=False)

In [ ]:
path+'/00_QA_unrelated_df_all(2a).csv'

'/content/drive/MyDrive/_Lutfi/_Course/Material/Research/_25 rerun new data/dataset/00_QA_unrelated_df_all(2a).csv'

In [ ]:
Q_all_dataset.groupby('relationship').count()

,id1,tahun1,input_x_v2,id2,tahun2,input_y_v2,penjelasan
relationship,,,,,,,
equivalent,563,563,563,563,563,563,563
lebih khusus dari,4,4,4,4,4,4,4
lebih umum dari,63,63,63,63,63,63,63
tidak ada hubungan,48116,48116,48116,48116,48116,48116,48116

In [ ]:
QA_all_dataset.groupby('relationship').count()

,id,year,input_x,id2,year2,input_y,penjelasan
relationship,,,,,,,
equivalent,1349,1349,1349,1349,1349,1349,1349
lebih khusus dari,270,270,270,270,270,270,270
lebih umum dari,111,111,111,111,111,111,111
tidak ada hubungan,599745,599745,599745,599745,599745,599745,599745

## reverse more aggregated and more detailed to increase number of inclusion rows

In [ ]:
Q_aggregated_df_reversed = Q_aggregated_df.copy()
Q_aggregated_df_reversed.rename(columns={'id1':'id2', 'tahun1':'tahun2', 'input_x_v2':'input_y_v2', 'id2':'id1', 'tahun2':'tahun1', 'input_y_v2':'input_x_v2'}, inplace=True)

Q_detailed_df_reversed = Q_detailed_df.copy()
Q_detailed_df_reversed.rename(columns={'id1':'id2', 'tahun1':'tahun2', 'input_x_v2':'input_y_v2', 'id2':'id1', 'tahun2':'tahun1', 'input_y_v2':'input_x_v2'}, inplace=True)

Q_aggregated_df_final = pd.concat([Q_aggregated_df, Q_detailed_df_reversed], ignore_index=True)
Q_detailed_df_final = pd.concat([Q_detailed_df, Q_aggregated_df_reversed], ignore_index=True)

In [ ]:
QA_aggregated_df_reversed = QA_aggregated_df.copy()
QA_aggregated_df_reversed.rename(columns={'id':'id2', 'year':'year2', 'input_x':'input_y', 'id2':'id', 'year2':'year', 'input_y':'input_x'}, inplace=True)

QA_detailed_df_reversed = QA_detailed_df.copy()
QA_detailed_df_reversed.rename(columns={'id':'id2', 'year':'year2', 'input_x':'input_y', 'id2':'id', 'year2':'year', 'input_y':'input_x'}, inplace=True)

QA_aggregated_df_final = pd.concat([QA_aggregated_df, QA_detailed_df_reversed], ignore_index=True)
QA_detailed_df_final = pd.concat([QA_detailed_df, QA_aggregated_df_reversed], ignore_index=True)

In [ ]:
print(Q_related_only_dataset.shape)

print("\n")
print(Q_equivalent_df.shape)
print(Q_aggregated_df.shape)
print(Q_detailed_df.shape)

print("\n after reversed added\n")
print(Q_equivalent_df.shape)
print(Q_aggregated_df_final.shape)
print(Q_detailed_df_final.shape)

print("\n\n")

print(QA_related_only_dataset.shape)
print("\n")
print(QA_equivalent_df.shape)
print(QA_aggregated_df.shape)
print(QA_detailed_df.shape)
print("\n after reversed added\n")
print(QA_equivalent_df.shape)
print(QA_aggregated_df_final.shape)
print(QA_detailed_df_final.shape)

(630, 15)


(563, 8)
(63, 8)
(4, 8)

 after reversed added

(563, 8)
(67, 8)
(67, 8)



(1730, 19)


(1349, 8)
(111, 8)
(270, 8)

 after reversed added

(1349, 8)
(381, 8)
(381, 8)

## sampled unrelated data

In [ ]:
num_related_q_pairs = len(Q_equivalent_df)+len(Q_aggregated_df_final)+len(Q_detailed_df_final)
Q_unrelated_sampled_df = Q_unrelated_df_all.sample(n=num_related_q_pairs, random_state=42)

print(f"Original Q_unrelated_df_all shape: {Q_unrelated_df_all.shape}")
print(f"Number of Q related only dataset rows: {num_related_q_pairs}")
print(f"Sampled Q_unrelated_sampled_df shape: {Q_unrelated_sampled_df.shape}")
Q_unrelated_sampled_df.to_csv(path+'/Q_unrelated_sampled_df_v2(2).csv', index=False) #v2 pastikan tahun1<tahun2 tidak ada tahun1>=tahun2

Original Q_unrelated_df_all shape: (48116, 8)
Number of Q related only dataset rows: 697
Sampled Q_unrelated_sampled_df shape: (697, 8)

In [ ]:
num_related_qa_pairs = len(QA_equivalent_df)+len(QA_aggregated_df_final)+len(QA_detailed_df_final)
QA_unrelated_sampled_df = QA_unrelated_df_all.sample(n=num_related_qa_pairs, random_state=42)

print(f"Original QA_unrelated_df_all shape: {QA_unrelated_df_all.shape}")
print(f"Number of QA related only dataset rows: {num_related_qa_pairs}")
print(f"Sampled QA_unrelated_sampled_df shape: {QA_unrelated_sampled_df.shape}")
QA_unrelated_sampled_df.to_csv(path+'/QA_unrelated_sampled_df_v2(2).csv', index=False)

Original QA_unrelated_df_all shape: (599745, 8)
Number of QA related only dataset rows: 2111
Sampled QA_unrelated_sampled_df shape: (2111, 8)

## create balanced dataset

In [ ]:
Q_equivalent_df['relationship'] = 'equivalent'
Q_aggregated_df_final['relationship'] = 'lebih umum dari'
Q_detailed_df_final['relationship'] = 'lebih khusus dari'
Q_unrelated_sampled_df['relationship'] = 'tidak ada hubungan'
q_balanced_df = pd.concat([Q_equivalent_df, Q_aggregated_df_final, Q_detailed_df_final, Q_unrelated_sampled_df], ignore_index=True)

QA_equivalent_df['relationship'] = 'equivalent'
QA_aggregated_df_final['relationship'] = 'lebih umum dari'
QA_detailed_df_final['relationship'] = 'lebih khusus dari'
QA_unrelated_sampled_df['relationship'] = 'tidak ada hubungan'
qa_balanced_df = pd.concat([QA_equivalent_df, QA_aggregated_df_final, QA_detailed_df_final, QA_unrelated_sampled_df], ignore_index=True)

q_balanced_df.to_csv(path+'/q_balanced_df(2).csv', index=False)
qa_balanced_df.to_csv(path+'/qa_balanced_df(2).csv', index=False)

In [ ]:
Q_equivalent_df['relationship'] = 'equivalent'
Q_aggregated_df_final['relationship'] = 'lebih umum dari'
Q_detailed_df_final['relationship'] = 'lebih khusus dari'
Q_top_hard_neg['relationship'] = 'tidak ada hubungan'
q_hard_balanced_df = pd.concat([Q_equivalent_df, Q_aggregated_df_final, Q_detailed_df_final, Q_top_hard_neg], ignore_index=True)

QA_equivalent_df['relationship'] = 'equivalent'
QA_aggregated_df_final['relationship'] = 'lebih umum dari'
QA_detailed_df_final['relationship'] = 'lebih khusus dari'
QA_top_hard_neg['relationship'] = 'tidak ada hubungan'
qa_hard_balanced_df = pd.concat([QA_equivalent_df, QA_aggregated_df_final, QA_detailed_df_final, QA_top_hard_neg], ignore_index=True)

q_hard_balanced_df.to_csv(path+'/q_hard_balanced_df(2).csv', index=False)
qa_hard_balanced_df.to_csv(path+'/qa_hard_balanced_df(2).csv', index=False)

# Generate Synthetic Dataset

##import

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
from google.colab import userdata
# !pip install llama-index-llms-groq llama-index Groq  --quiet

# from llama_index.llms.groq import Groq
# from llama_index.core.llms import ChatMessage
!pip install openai groq

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.26.0)
Collecting groq
  Downloading groq-1.1.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Downloading groq-1.1.1-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.7/139.7 kB 5.8 MB/s eta 0:00:00
Installing collected packages: groq
Successfully installed groq-1.1.1

##load balanced golden dataset

In [ ]:
survei_dataset_balanced= pd.read_csv('/content/drive/MyDrive/yourpath/balanced dataset/dataset Q/survei_dataset_balanced_v2.csv') #after cleaning
survei_dataset_QA_balanced= pd.read_csv('/content/drive/MyDrive/yourpath/balanced dataset/dataset QA/survei_dataset_QA_balanced_nolabel_fix.csv', sep=";", encoding='cp1252') #after cleaning and fixing the dataset

In [ ]:
map_relationship = {
    'equivalent': 'equivalen',
    'lebih umum dari': 'lebih agregat',
    'lebih khusus dari': 'lebih detail',
    'tidak ada hubungan': 'tidak ada hubungan'
}
survei_dataset_balanced['relationship_v2']=survei_dataset_balanced['relationship'].map(map_relationship)
survei_dataset_QA_balanced['relationship_v2']=survei_dataset_QA_balanced['relationship'].map(map_relationship)

In [ ]:
Qlist1=survei_dataset_balanced[['id1','input_x_v2']]
Qlist2=survei_dataset_balanced[['id2','input_y_v2']]
QAlist1=survei_dataset_QA_balanced[['id','input_x']]
QAlist2=survei_dataset_QA_balanced[['id2','input_y']]
Qlist1.head()

          id1                                         input_x_v2
0  2010-B1P01  <blok> Pengenalan tempat </blok><pertanyaan> P...
1  2010-B1P02  <blok> Pengenalan tempat </blok><pertanyaan> K...
2  2010-B1P05  <blok> Pengenalan tempat </blok><pertanyaan> K...
3    2010-HUB  <blok> Keterangan anggota rumah tangga </blok>...
4     2010-JK  <blok> Keterangan anggota rumah tangga </blok>...

In [ ]:
Qlist1.rename(columns={'id1':'id', 'input_x_v2':'input'}, inplace=True)
Qlist2.rename(columns={'id2':'id', 'input_y_v2':'input'}, inplace=True)
QAlist1.rename(columns={'id':'id', 'input_x':'input'}, inplace=True)
QAlist2.rename(columns={'id2':'id', 'input_y':'input'}, inplace=True)

/tmp/ipykernel_9903/1545273921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Qlist1.rename(columns={'id1':'id', 'input_x_v2':'input'}, inplace=True)
/tmp/ipykernel_9903/1545273921.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Qlist2.rename(columns={'id2':'id', 'input_y_v2':'input'}, inplace=True)
/tmp/ipykernel_9903/1545273921.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  QAlist1.rename(columns={'id':'id', 'input_x':'input'}, inplace=True)
/tmp/ipykernel_9903/1545273921.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  QAlist2.rename(columns={'id2':'id', 'input_y':'input'}, inplace=True)

In [ ]:
Qlist=pd.concat([Qlist1,Qlist2])
QAlist=pd.concat([QAlist1,QAlist2])
Qlist= Qlist.drop_duplicates()
QAlist=QAlist.drop_duplicates()

In [ ]:
QAlist.shape

(1496, 2)

In [ ]:
# modelname="openai/gpt-oss-120b"

In [ ]:

# from openai import OpenAI
# import os
# client = OpenAI(
#     api_key=userdata.get('STIS_GROQ_API_KEY2'),
#     base_url="https://api.groq.com/openai/v1",
# )

# response = client.responses.create(
#     input="Explain the importance of fast language models",
#     model="openai/gpt-oss-20b",
# )
# print(response.output_text)

## paraphrase input text

In [ ]:
from groq import Groq


from openai import OpenAI
import os
client = OpenAI(
    api_key=userdata.get('STIS_GROQ_API_KEY2'),
    base_url="https://api.groq.com/openai/v1",
)

def paraphrase(input):
  response = client.responses.create(
      input=f'''Parafrase input berikut dengan mempertahankan format tag yang diberikan. Tampilkan hanya hasil parafrase tanpa tambahan text atau penjelasan lainnya.
      input:
      {input}
      ''',
      model="openai/gpt-oss-20b",
  )
  return response.output_text

In [ ]:
Qlist['paraphase'] = None
QAlist['paraphase'] = None
for idx, row in Qlist.iterrows():
  Qlist.loc[idx, 'paraphase'] = paraphrase(row['input'])

for idx, row in QAlist.iterrows():
  QAlist.loc[idx, 'paraphase'] = paraphrase(row['input'])

In [ ]:
Qlist.to_csv(path+'/Q_hard_parafrase_list(2).csv')
QAlist.to_csv(path+'/QA_hard_parafrase_list(2).csv')

In [ ]:
survei_dataset_balanced.columns

Index(['id1', 'tahun1', 'input_x_v2', 'id2', 'tahun2', 'input_y_v2',
       'relationship', 'penjelasan', 'sim_score', 'relationship_v2'],
      dtype='object')

In [ ]:
survei_dataset_balanced_paraphrase = survei_dataset_balanced.merge(Qlist, left_on='id1', right_on='id', how='left', suffixes=('_original', '_Qlist'))
survei_dataset_balanced_paraphrase.columns

Index(['id1', 'tahun1', 'input_x_v2', 'id2', 'tahun2', 'input_y_v2',
       'relationship', 'penjelasan', 'sim_score', 'relationship_v2', 'id',
       'input', 'paraphase'],
      dtype='object')

In [ ]:
survei_dataset_balanced_paraphrase.rename(columns={'paraphase':'paraphrase_input_x_v2'}, inplace=True)

In [ ]:
survei_dataset_balanced_paraphrase = survei_dataset_balanced_paraphrase.merge(Qlist, left_on='id2', right_on='id', how='left', suffixes=('_original', '_Qlist'))

In [ ]:
survei_dataset_balanced_paraphrase.rename(columns={'paraphase':'paraphrase_input_y_v2'}, inplace=True)
survei_dataset_balanced_paraphrase.columns

Index(['id1', 'tahun1', 'input_x_v2', 'id2', 'tahun2', 'input_y_v2',
       'relationship', 'penjelasan', 'sim_score', 'relationship_v2',
       'id_original', 'input_original', 'paraphrase_input_x_v2', 'id_Qlist',
       'input_Qlist', 'paraphrase_input_y_v2'],
      dtype='object')

In [ ]:
survei_dataset_balanced_paraphrase.drop(columns=['id_original','input_original','id_Qlist','input_Qlist'], inplace=True)

In [ ]:
survei_dataset_balanced_paraphrase.to_csv(path+'/survei_dataset_hard_balanced_paraphrase(2).csv')

In [ ]:
survei_dataset_QA_balanced.columns

Index(['id', 'year', 'input_x', 'id2', 'year2', 'input_y', 'relationship',
       'penjelasan', 'sim_score', 'relationship_v2'],
      dtype='object')

In [ ]:
survei_dataset_QA_balanced_paraphrase = survei_dataset_QA_balanced.merge(QAlist, left_on=['id','input_x'], right_on=['id','input'], how='left', suffixes=('_original', '_QAlist'))
survei_dataset_QA_balanced_paraphrase

,id,year,input_x,id2,year2,input_y,relationship,penjelasan,sim_score,relationship_v2,input,paraphase
0,2010-B1P05-1,2010,<blok> Pengenalan tempat </blok><pertanyaan> K...,2012-B1P05-1,2012,<blok> Pengenalan tempat </blok><pertanyaan> K...,equivalent,karena keduanya mempunyai arti semantik yang sama,NaN,equivalen,<blok> Pengenalan tempat </blok><pertanyaan> K...,<blok> Pengenalan lokasi </blok><pertanyaan> T...
1,2010-B1P05- 2,2010,<blok> Pengenalan tempat </blok><pertanyaan> K...,2012-B1P05- 2,2012,<blok> Pengenalan tempat </blok><pertanyaan> K...,equivalent,karena keduanya mempunyai arti semantik yang sama,NaN,equivalen,<blok> Pengenalan tempat </blok><pertanyaan> K...,<blok> Perkenalan lokasi </blok><pertanyaan> P...
2,2010-HUB-1,2010,<blok> Keterangan anggota rumah tangga </blok>...,2012-HUB-1,2012,<blok> Keterangan anggota rumah tangga </blok>...,equivalent,karena keduanya mempunyai arti semantik yang sama,NaN,equivalen,<blok> Keterangan anggota rumah tangga </blok>...,<blok> Deskripsi anggota keluarga </blok><pert...
3,2010-HUB- 2,2010,<blok> Keterangan anggota rumah tangga </blok>...,2012-HUB- 2,2012,<blok> Keterangan anggota rumah tangga </blok>...,equivalent,karena keduanya mempunyai arti semantik yang sama,NaN,equivalen,<blok> Keterangan anggota rumah tangga </blok>...,<blok> Informasi anggota rumah tangga </blok><...
4,2010-HUB- 3,2010,<blok> Keterangan anggota rumah tangga </blok>...,2012-HUB- 3,2012,<blok> Keterangan anggota rumah tangga </blok>...,equivalent,karena keduanya mempunyai arti semantik yang sama,NaN,equivalen,<blok> Keterangan anggota rumah tangga </blok>...,<blok> Informasi tentang anggota keluarga </bl...
...,...,...,...,...,...,...,...,...,...,...,...,...
4217,2012-B5P8B- 91,2012,<blok> Kegiatan seminggu yang lalu </blok><per...,2017-b5_r1a-13,2017,<blok> Karakteristik umum </blok><pertanyaan> ...,tidak ada hubungan,kedua kategori tersebut tidak berkaitan atau b...,0.162010,tidak ada hubungan,<blok> Kegiatan seminggu yang lalu </blok><per...,<blok> Kegiatan selama seminggu terakhir </blo...
4218,2015-B5_R25-3,2015,<blok> Pengalaman kerja </blok><pertanyaan> Al...,2020-klasifikas-1,2020,<blok> </blok><pertanyaan> Klasifikasi Desa/ ...,tidak ada hubungan,kedua kategori tersebut tidak berkaitan atau b...,0.155540,tidak ada hubungan,<blok> Pengalaman kerja </blok><pertanyaan> Al...,<blok> Riwayat kerja </blok><pertanyaan> Motif...
4219,2017-b5_r1a-15,2017,<blok> Karakteristik umum </blok><pertanyaan> ...,2020-r31b-1,2020,<blok> Kegiatan lain </blok><pertanyaan> Dalam...,tidak ada hubungan,kedua kategori tersebut tidak berkaitan atau b...,0.128881,tidak ada hubungan,<blok> Karakteristik umum </blok><pertanyaan> ...,<blok> Informasi umum </blok><pertanyaan> Ting...
4220,2015-B5_R1A-12,2015,<blok> Pendidikan </blok><pertanyaan> Apakah p...,2020-r19c-2,2020,<blok> </blok><pertanyaan> Apakah Anda melaku...,tidak ada hubungan,kedua kategori tersebut tidak berkaitan atau b...,0.118682,tidak ada hubungan,<blok> Pendidikan </blok><pertanyaan> Apakah p...,<blok> Pendidikan </blok><pertanyaan> Apa ting...
4221,2012-B5P15E-1,2012,<blok> Pekerjaan utama </blok><pertanyaan> Apa...,2020-r4-2,2020,<blok> </blok><pertanyaan> Apakah status perk...,tidak ada hubungan,kedua kategori tersebut tidak berkaitan atau b...,0.091357,tidak ada hubungan,<blok> Pekerjaan utama </blok><pertanyaan> Apa...,<blok> Pekerjaan utama </blok><pertanyaan> Jen...

In [ ]:
survei_dataset_QA_balanced_paraphrase.rename(columns={'paraphase':'paraphrase_input_x'}, inplace=True)

In [ ]:
survei_dataset_QA_balanced_paraphrase = survei_dataset_QA_balanced_paraphrase.merge(QAlist, left_on=['id2','input_y'], right_on=['id','input'], how='left', suffixes=('_original', '_QAlist'))

In [ ]:
survei_dataset_QA_balanced_paraphrase.rename(columns={'paraphase':'paraphrase_input_y'}, inplace=True)

In [ ]:
survei_dataset_QA_balanced_paraphrase.rename(columns={'id_original':'id'}, inplace=True)

In [ ]:
survei_dataset_QA_balanced_paraphrase.columns

Index(['id', 'year', 'input_x', 'id2', 'year2', 'input_y', 'relationship',
       'penjelasan', 'sim_score', 'relationship_v2', 'input_original',
       'paraphrase_input_x', 'id_QAlist', 'input_QAlist',
       'paraphrase_input_y'],
      dtype='object')

In [ ]:
survei_dataset_QA_balanced_paraphrase.drop(columns=['input_original','id_QAlist','input_QAlist'], inplace=True)

In [ ]:
survei_dataset_QA_balanced_paraphrase.to_csv(path+'/survei_dataset_QA_hard_balanced_paraphrase(2).csv')

## load paraphrase dataset for reasoning generation

In [ ]:
survei_dataset_balanced_paraphrase = pd.read_csv(path+'/survei_dataset_balanced_paraphrase(2).csv')
survei_dataset_QA_balanced_paraphrase = pd.read_csv(path+'/survei_dataset_QA_balanced_paraphrase(2).csv')

In [ ]:
# maprelationship = {
#     'equivalent': 'equivalen',
#     'lebih umum dari': 'lebih agregat',
#     'lebih khusus dari': 'lebih detail',
#     'tidak ada hubungan': 'tidak ada hubungan'
# }
# survei_dataset_balanced_paraphrase['relationship_v2']=survei_dataset_balanced_paraphrase['relationship'].map(maprelationship)
# survei_dataset_QA_balanced_paraphrase['relationship_v2']=survei_dataset_QA_balanced_paraphrase['relationship'].map(maprelationship)

In [ ]:
survei_dataset_balanced_paraphrase.columns

Index(['Unnamed: 0', 'id1', 'tahun1', 'input_x_v2', 'id2', 'tahun2',
       'input_y_v2', 'relationship', 'penjelasan', 'relationship_v2',
       'paraphrase_input_x_v2', 'paraphrase_input_y_v2'],
      dtype='object')

In [ ]:
survei_dataset_QA_balanced_paraphrase.columns

Index(['Unnamed: 0', 'id', 'year', 'input_x', 'id2', 'year2', 'input_y',
       'relationship', 'penjelasan', 'relationship_v2', 'paraphrase_input_x',
       'paraphrase_input_y'],
      dtype='object')

## generate reasoning

In [ ]:
from groq import Groq


from openai import OpenAI
import os
client = OpenAI(
    api_key=userdata.get('STIS_GROQ_API_KEY2'),
    base_url="https://api.groq.com/openai/v1",
)

def reasoning(entitas1, hubungan, entitas2, ent1, ent2, reason):
  response = client.responses.create(
      input=f'''Jelaskan mengapa secara semantik "{entitas1}" {hubungan} terhadap "{entitas2}", seperti "{ent1}" {hubungan} terhadap "{ent2}" dengan alasan {reason}. Tampilkan hanya penjelasan inti tanpa tambahan text atau penjelasan lainnya.
      ''',
      model="openai/gpt-oss-20b",
  )
  return response.output_text

In [ ]:
# reasoning(row['paraphrase_input_x_v2'], row['relationship_v2'], row['paraphrase_input_y_v2'],row['input_x_v2'],row['input_y_v2'],row['penjelasan'])

In [ ]:
survei_dataset_balanced_paraphrase['penjelasan_para'] = None
for idx, row in survei_dataset_balanced_paraphrase.iterrows():
  survei_dataset_balanced_paraphrase.loc[idx, 'penjelasan_para'] = reasoning(row['paraphrase_input_x_v2'], row['relationship_v2'], row['paraphrase_input_y_v2'],row['input_x_v2'],row['input_y_v2'],row['penjelasan'])
survei_dataset_balanced_paraphrase.to_csv(path+'/survei_dataset_balanced_paraphrase_reasoning_v2(2).csv')

In [ ]:
survei_dataset_QA_balanced_paraphrase['penjelasan_para'] = None
for idx, row in survei_dataset_QA_balanced_paraphrase.iterrows():
  survei_dataset_QA_balanced_paraphrase.loc[idx, 'penjelasan_para'] = reasoning(row['paraphrase_input_x'], row['relationship_v2'], row['paraphrase_input_y'],row['input_x'],row['input_y'],row['penjelasan'])
survei_dataset_QA_balanced_paraphrase.to_csv(path+'/survei_dataset_QA_balanced_paraphrase_reasoning_v2(2).csv')

In [ ]:
print(path+'survei_dataset_balanced_paraphrase_reasoning_v2(2).csv')

In [ ]:
survei_dataset_QA_balanced_paraphrase[['penjelasan','penjelasan_para']]

,penjelasan,penjelasan_para
0,karena keduanya mempunyai arti semantik yang sama,Karena setiap elemen di kedua string merupakan...
1,karena keduanya mempunyai arti semantik yang sama,Kedua rangkaian menyatakan: \n- `<blok>` meng...
2,karena keduanya mempunyai arti semantik yang sama,Kedua struktur menggambarkan hubungan anggota ...
3,karena keduanya mempunyai arti semantik yang sama,- “kepala rumah tangga” = “pemimpin keluarga” ...
4,karena keduanya mempunyai arti semantik yang sama,Kedua frasa memiliki makna yang sama karena:\n...
...,...,...
4217,kedua kategori tersebut tidak berkaitan atau b...,Kegiatan mencari kerja / menyiapkan usaha bers...
4218,kedua kategori tersebut tidak berkaitan atau b...,Kedua blok mengacu pada domain yang berbeda: s...
4219,kedua kategori tersebut tidak berkaitan atau b...,Durasi pekerjaan (berapa lama) hanya memberi d...
4220,kedua kategori tersebut tidak berkaitan atau b...,Pertanyaan pertama menanyakan lama pengalaman ...
4221,kedua kategori tersebut tidak berkaitan atau b...,Karena aktivitas pencarian kerja/usaha yang di...

In [ ]:
from IPython.display import Audio, display
import numpy as np

sample_rate = 44100  # samples per second
duration = 4.0  # seconds
frequency = 440.0  # Hz (A4 note)

t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)
waveform = np.sin(2 * np.pi * frequency * t)

display(Audio(waveform, rate=sample_rate))

In [ ]:
survei_dataset_balanced_paraphrase[survei_dataset_balanced_paraphrase['relationship']=='lebih khusus dari'].head()

,Unnamed: 0,id1,tahun1,input_x_v2,id2,tahun2,input_y_v2,relationship,penjelasan,relationship_v2,paraphrase_input_x_v2,paraphrase_input_y_v2,penjelasan_para
630,630,2017-b5_r30c11,2017,<blok> Pekerjaan utama </blok><pertanyaan> JIK...,2020-r14a1,2020,<blok> Umum Responden </blok><pertanyaan> Bera...,lebih khusus dari,karena pertanyaan kedua menanyakan gaji secara...,lebih detail,<blok> Pekerjaan utama </blok><pertanyaan> JIK...,<blok> Umum Responden </blok><pertanyaan> Bera...,Pertanyaan pertama menanyakan gaji bersih spes...
631,631,2017-b5_r30c12,2017,<blok> Pekerjaan utama </blok><pertanyaan> JIK...,2020-r14a2,2020,<blok> Umum Responden </blok><pertanyaan> Bera...,lebih khusus dari,karena pertanyaan kedua menanyakan gaji secara...,lebih detail,<blok> Pekerjaan utama </blok><pertanyaan> Apa...,<blok> Umum Responden </blok><pertanyaan> Bera...,Pertanyaan pertama lebih detail karena mengacu...
632,632,2017-b5_r30c21,2017,<blok> Pekerjaan utama </blok><pertanyaan> Upa...,2020-r14a1,2020,<blok> Umum Responden </blok><pertanyaan> Bera...,lebih khusus dari,karena pertanyaan kedua menanyakan Upah Lembur...,lebih detail,<blok> Tugas pokok </blok><pertanyaan> Gaji le...,<blok> Umum Responden </blok><pertanyaan> Bera...,Karena pertanyaan kedua secara spesifik memint...
633,633,2017-b5_r30c22,2017,<blok> Pekerjaan utama </blok><pertanyaan> Upa...,2020-r14a2,2020,<blok> Umum Responden </blok><pertanyaan> Bera...,lebih khusus dari,karena pertanyaan kedua menanyakan Upah Lembur...,lebih detail,<blok> Tugas Utama </blok><pertanyaan> Gaji Le...,<blok> Umum Responden </blok><pertanyaan> Bera...,"Pertanyaan tentang upah lembur, transportasi, ..."
634,634,2012-B5P13A,2012,<blok> Pekerjaan utama </blok><pertanyaan> Ber...,2010-B5P11A,2010,<blok> Pekerjaan utama </blok><pertanyaan> Ber...,lebih khusus dari,karena pertanyaan pertama menanyakan gaji seca...,lebih detail,<blok> Pekerjaan utama </blok><pertanyaan> Ber...,<blok> Pekerjaan utama </blok><pertanyaan> Ber...,Karena yang pertama menyebutkan “total upah be...

# Split synthetic dataset 80 20, gold as test (random stratified based on the relationship and type QA)

##load dataset

In [ ]:
# survei_dataset_balanced_paraphrase= pd.read_csv('/content/drive/MyDrive/yourpath/balanced dataset/dataset Q/survei_dataset_balanced_paraphrase_reasoning_v2.csv')
# survei_dataset_QA_balanced_paraphrase= pd.read_csv('/content/drive/MyDrive/yourpath/balanced dataset/dataset QA/survei_dataset_QA_balanced_paraphrase_reasoning_v2.csv')
# survei_dataset_balanced= pd.read_csv('/content/drive/MyDrive/yourpath/balanced dataset/dataset Q/survei_dataset_balanced_paraphrase_reasoning.csv')
# survei_dataset_QA_balanced= pd.read_csv('/content/drive/MyDrive/yourpath/balanced dataset/dataset QA/survei_dataset_QA_balanced_paraphrase_reasoning.csv')

path = '/content/drive/MyDrive/yourpath'
survei_dataset_balanced= pd.read_csv(path+'/q_hard_balanced_df(2).csv')
survei_dataset_balanced_paraphrase= pd.read_csv(path+'/survei_dataset_hard_balanced_paraphrase(2).csv')
survei_dataset_QA_balanced= pd.read_csv(path+'/qa_hard_balanced_df(2).csv')
survei_dataset_QA_balanced_paraphrase= pd.read_csv(path+'/survei_dataset_QA_hard_balanced_paraphrase(2).csv')
# survei_dataset_balanced= pd.read_csv(path+'/q_hard_balanced_df(2).csv')
# survei_dataset_balanced_paraphrase= pd.read_csv(path+'/survei_dataset_hard_balanced_paraphrase(2).csv')
# survei_dataset_QA_balanced= pd.read_csv(path+'/qa_hard_balanced_df(2).csv')
# survei_dataset_QA_balanced_paraphrase= pd.read_csv(path+'/survei_dataset_QA_hard_balanced_paraphrase(2).csv')

In [ ]:
print(survei_dataset_balanced.columns)
print(survei_dataset_QA_balanced.columns)

print(survei_dataset_balanced_paraphrase.columns)
print(survei_dataset_QA_balanced_paraphrase.columns)

Index(['id1', 'tahun1', 'input_x_v2', 'id2', 'tahun2', 'input_y_v2',
       'relationship', 'penjelasan', 'sim_score'],
      dtype='object')
Index(['id', 'year', 'input_x', 'id2', 'year2', 'input_y', 'relationship',
       'penjelasan', 'sim_score'],
      dtype='object')
Index(['Unnamed: 0', 'id1', 'tahun1', 'input_x_v2', 'id2', 'tahun2',
       'input_y_v2', 'relationship', 'penjelasan', 'sim_score',
       'relationship_v2', 'paraphrase_input_x_v2', 'paraphrase_input_y_v2'],
      dtype='object')
Index(['Unnamed: 0', 'id', 'year', 'input_x', 'id2', 'year2', 'input_y',
       'relationship', 'penjelasan', 'sim_score', 'relationship_v2',
       'paraphrase_input_x', 'paraphrase_input_y'],
      dtype='object')

In [ ]:
# survei_dataset_balanced_x = pd.merge(survei_dataset_balanced[['id1','tahun1','input_x_v2','id2','tahun2','input_y_v2','relationship']], survei_dataset_balanced_paraphrase[['tahun1', 'input_x_v2', 'tahun2','input_y_v2', 'relationship', 'relationship_v2','paraphrase_input_x_v2', 'paraphrase_input_y_v2', 'penjelasan']], left_on=['tahun1', 'input_x_v2', 'tahun2','input_y_v2','relationship'], right_on=['tahun1', 'input_x_v2', 'tahun2','input_y_v2','relationship'], how='left')
# survei_dataset_balanced_x.to_csv(path+'/survei_dataset_balanced_paraphrase_reasoning_v2.csv')
# survei_dataset_balanced_x.drop(columns=['penjelasan']).to_csv(path+'/survei_dataset_balanced_paraphrase.csv')

In [ ]:
import pandas as pd

datasets = {
    "survei_dataset_balanced_paraphrase": survei_dataset_balanced_paraphrase,
    "survei_dataset_QA_balanced_paraphrase": survei_dataset_QA_balanced_paraphrase,
}

# Gabungkan semua value_counts menjadi satu tabel
counts_table = pd.concat(
    {name: df["relationship"].value_counts(dropna=False) for name, df in datasets.items()},
    axis=1
).fillna(0).astype(int)

# (opsional) urutkan baris label sesuai total terbanyak
counts_table = counts_table.loc[counts_table.sum(axis=1).sort_values(ascending=False).index]

# (opsional) tambah total per kolom
counts_table.loc["TOTAL"] = counts_table.sum(axis=0)

display(counts_table)          # Jupyter/Colab
# print(counts_table.to_string())  # kalau mau versi print juga

,survei_dataset_balanced_paraphrase,survei_dataset_QA_balanced_paraphrase
relationship,,
tidak ada hubungan,697,2111
equivalent,563,1349
lebih umum dari,67,381
lebih khusus dari,67,381
TOTAL,1394,4222

##split

In [ ]:
from sklearn.model_selection import train_test_split

print("Columns in survei_dataset_Q_balanced:")
print(survei_dataset_balanced_paraphrase.columns)

Q_train_df, Q_valid_df = train_test_split(survei_dataset_balanced_paraphrase, test_size=0.2, random_state=42, stratify=survei_dataset_balanced_paraphrase['relationship'])

print("Columns in survei_dataset_QA_balanced:")
print(survei_dataset_QA_balanced_paraphrase.columns)

QA_train_df, QA_valid_df = train_test_split(survei_dataset_QA_balanced_paraphrase, test_size=0.2, random_state=42, stratify=survei_dataset_QA_balanced_paraphrase['relationship'])

Columns in survei_dataset_Q_balanced:
Index(['Unnamed: 0', 'id1', 'tahun1', 'input_x_v2', 'id2', 'tahun2',
       'input_y_v2', 'relationship', 'penjelasan', 'sim_score',
       'relationship_v2', 'paraphrase_input_x_v2', 'paraphrase_input_y_v2'],
      dtype='object')
Columns in survei_dataset_QA_balanced:
Index(['Unnamed: 0', 'id', 'year', 'input_x', 'id2', 'year2', 'input_y',
       'relationship', 'penjelasan', 'sim_score', 'relationship_v2',
       'paraphrase_input_x', 'paraphrase_input_y'],
      dtype='object')

In [ ]:
Q_test_df = survei_dataset_balanced_paraphrase #only use original input
QA_test_df = survei_dataset_QA_balanced_paraphrase #only use original input

In [ ]:
import pandas as pd

datasets = {
    "Q_train": Q_train_df,
    "Q_valid": Q_valid_df,
    "Q_test" : Q_test_df,
    "QA_train": QA_train_df,
    "QA_valid": QA_valid_df,
    "QA_test" : QA_test_df,

}

# Gabungkan semua value_counts menjadi satu tabel
counts_table = pd.concat(
    {name: df["relationship"].value_counts(dropna=False) for name, df in datasets.items()},
    axis=1
).fillna(0).astype(int)

# (opsional) urutkan baris label sesuai total terbanyak
counts_table = counts_table.loc[counts_table.sum(axis=1).sort_values(ascending=False).index]

# (opsional) tambah total per kolom
counts_table.loc["TOTAL"] = counts_table.sum(axis=0)

display(counts_table)          # Jupyter/Colab
# print(counts_table.to_string())  # kalau mau versi print juga

                    Q_train  Q_valid  Q_test  QA_train  QA_valid  QA_test
relationship
tidak ada hubungan      557      140     697      1688       423     2111
equivalent              450      113     563      1079       270     1349
lebih khusus dari        54       13      67       305        76      381
lebih umum dari          54       13      67       305        76      381
TOTAL                  1115      279    1394      3377       845     4222

## rearrange

In [ ]:
# path = '/content/drive/MyDrive/yourpath/balanced dataset/split70_10_20/'
# !ls "/content/drive/MyDrive/yourpath/balanced dataset/split70_10_20"

In [ ]:
Q_train_df.columns

Index(['Unnamed: 0', 'id1', 'tahun1', 'input_x_v2', 'id2', 'tahun2',
       'input_y_v2', 'relationship', 'penjelasan', 'sim_score',
       'relationship_v2', 'paraphrase_input_x_v2', 'paraphrase_input_y_v2'],
      dtype='object')

In [ ]:
QA_train_df.columns

Index(['Unnamed: 0', 'id', 'year', 'input_x', 'id2', 'year2', 'input_y',
       'relationship', 'penjelasan', 'sim_score', 'relationship_v2',
       'paraphrase_input_x', 'paraphrase_input_y'],
      dtype='object')

In [ ]:
#pisahkan dulu ori dan synt untuk bisa di merge
# Q_train_df_synt =  Q_train_df[['id1','tahun1', 'paraphrase_input_x_v2', 'id2',  'tahun2', 'paraphrase_input_y_v2','relationship','relationship_v2','penjelasan_para']]
# Q_valid_df_synt =  Q_valid_df[['id1','tahun1', 'paraphrase_input_x_v2', 'id2',  'tahun2', 'paraphrase_input_y_v2','relationship','relationship_v2','penjelasan_para']]
Q_train_df_synt =  Q_train_df[['id1','tahun1', 'paraphrase_input_x_v2', 'id2',  'tahun2', 'paraphrase_input_y_v2','relationship','relationship_v2']]
Q_valid_df_synt =  Q_valid_df[['id1','tahun1', 'paraphrase_input_x_v2', 'id2',  'tahun2', 'paraphrase_input_y_v2','relationship','relationship_v2']]

Q_test_df_ori = Q_test_df[['id1', 'tahun1', 'input_x_v2', 'id2',  'tahun2', 'input_y_v2','relationship','relationship_v2','penjelasan']]

In [ ]:
#pisahkan dulu ori dan synt untuk bisa di merge

# QA_train_df_synt =  QA_train_df[['id', 'year', 'paraphrase_input_x', 'id2',  'year2', 'paraphrase_input_y','relationship','relationship_v2','penjelasan_para']]
# QA_valid_df_synt =  QA_valid_df[['id','year', 'paraphrase_input_x', 'id2', 'year2', 'paraphrase_input_y','relationship','relationship_v2','penjelasan_para']]
QA_train_df_synt =  QA_train_df[['id', 'year', 'paraphrase_input_x', 'id2',  'year2', 'paraphrase_input_y','relationship','relationship_v2']]
QA_valid_df_synt =  QA_valid_df[['id','year', 'paraphrase_input_x', 'id2', 'year2', 'paraphrase_input_y','relationship','relationship_v2']]

QA_test_df_ori = QA_test_df[['id', 'year', 'input_x', 'id2',  'year2', 'input_y','relationship','relationship_v2','penjelasan']]

In [ ]:
#samakan nama kolom untuk bisa di merge
Q_test_df_ori.rename(columns={'id1':'id', 'tahun1':'year', 'input_x_v2':'input_x', 'id2':'id2', 'tahun2':'year2', 'input_y_v2':'input_y','penjelasan':'penjelasan'}, inplace=True)

# Q_train_df_synt.rename(columns={'id1':'id', 'tahun1':'year', 'paraphrase_input_x_v2':'input_x', 'id2':'id2', 'tahun2':'year2', 'paraphrase_input_y_v2':'input_y'}, inplace=True)
# Q_valid_df_synt.rename(columns={'id1':'id', 'tahun1':'year', 'paraphrase_input_x_v2':'input_x', 'id2':'id2', 'tahun2':'year2', 'paraphrase_input_y_v2':'input_y'}, inplace=True)
Q_train_df_synt.rename(columns={'id1':'id', 'tahun1':'year', 'paraphrase_input_x_v2':'input_x', 'id2':'id2', 'tahun2':'year2', 'paraphrase_input_y_v2':'input_y', 'penjelasan_para':'penjelasan'}, inplace=True)
Q_valid_df_synt.rename(columns={'id1':'id', 'tahun1':'year', 'paraphrase_input_x_v2':'input_x', 'id2':'id2', 'tahun2':'year2', 'paraphrase_input_y_v2':'input_y', 'penjelasan_para':'penjelasan'}, inplace=True)

QA_test_df_ori.rename(columns={'id':'id', 'year':'year', 'input_x':'input_x', 'id2':'id2', 'year2':'year2', 'input_y':'input_y', 'penjelasan':'penjelasan'}, inplace=True)

# QA_train_df_synt.rename(columns={'id':'id', 'year':'year', 'paraphrase_input_x':'input_x', 'id2':'id2', 'year2':'year2', 'paraphrase_input_y':'input_y'}, inplace=True)
# QA_valid_df_synt.rename(columns={'id':'id', 'year':'year', 'paraphrase_input_x':'input_x', 'id2':'id2', 'year2':'year2', 'paraphrase_input_y':'input_y'}, inplace=True)
QA_train_df_synt.rename(columns={'id':'id', 'year':'year', 'paraphrase_input_x':'input_x', 'id2':'id2', 'year2':'year2', 'paraphrase_input_y':'input_y', 'penjelasan_para':'penjelasan'}, inplace=True)
QA_valid_df_synt.rename(columns={'id':'id', 'year':'year', 'paraphrase_input_x':'input_x', 'id2':'id2', 'year2':'year2', 'paraphrase_input_y':'input_y', 'penjelasan_para':'penjelasan'}, inplace=True)

/tmp/ipykernel_9903/2336350547.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Q_test_df_ori.rename(columns={'id1':'id', 'tahun1':'year', 'input_x_v2':'input_x', 'id2':'id2', 'tahun2':'year2', 'input_y_v2':'input_y','penjelasan':'penjelasan'}, inplace=True)
/tmp/ipykernel_9903/2336350547.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Q_train_df_synt.rename(columns={'id1':'id', 'tahun1':'year', 'paraphrase_input_x_v2':'input_x', 'id2':'id2', 'tahun2':'year2', 'paraphrase_input_y_v2':'input_y', 'penjelasan_para':'penjelasan'}, inplace=True)
/tmp/ipykernel_9903/2336350547.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Q_valid_df_synt.rename(columns={'id1':'id', 'tahun1':'year', 'paraphrase_input_x_v2':'input_x', 'id2':'id2', 'tahun2':'year2', 'paraphrase_input_y_v2':'input_y', 'penjelasan_para':'penjelasan'}, inplace=True)
/tmp/ipykernel_9903/2336350547.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  QA_test_df_ori.rename(columns={'id':'id', 'year':'year', 'input_x':'input_x', 'id2':'id2', 'year2':'year2', 'input_y':'input_y', 'penjelasan':'penjelasan'}, inplace=True)
/tmp/ipykernel_9903/2336350547.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  QA_train_df_synt.rename(columns={'id':'id', 'year':'year', 'paraphrase_input_x':'input_x', 'id2':'id2', 'year2':'year2', 'paraphrase_input_y':'input_y', 'penjelasan_para':'penjelasan'}, inplace=True)
/tmp/ipykernel_9903/2336350547.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  QA_valid_df_synt.rename(columns={'id':'id', 'year':'year', 'paraphrase_input_x':'input_x', 'id2':'id2', 'year2':'year2', 'paraphrase_input_y':'input_y', 'penjelasan_para':'penjelasan'}, inplace=True)

In [ ]:
Q_train_df_synt.columns

Index(['id', 'year', 'input_x', 'id2', 'year2', 'input_y', 'relationship',
       'relationship_v2'],
      dtype='object')

In [ ]:
pathdata =path+'/T synth 80, V synth 20, T gold all (hard)'
train_df = pd.concat([ Q_train_df_synt, QA_train_df_synt])
valid_df = pd.concat([ Q_valid_df_synt, QA_valid_df_synt])
test_df = pd.concat([Q_test_df_ori, QA_test_df_ori])

train_df.to_csv(pathdata+'/train_df_synt.csv')
valid_df.to_csv(pathdata+'/valid_df_synt.csv')
test_df.to_csv(pathdata+'/test_df_ori.csv')

In [ ]:
!ls '/content/drive/MyDrive/yourpath/T synth 80, V synth 20, T gold all'

'test_df_ori (1).csv'  'train_df_synt (1).csv'	'valid_df_synt (1).csv'
 test_df_ori.csv        train_df_synt.csv	 valid_df_synt.csv

In [ ]:
test_df.tail()

,id,year,input_x,id2,year2,input_y,relationship,relationship_v2,penjelasan
4217,2012-B5P8B- 91,2012,<blok> Kegiatan seminggu yang lalu </blok><per...,2017-b5_r1a-13,2017,<blok> Karakteristik umum </blok><pertanyaan> ...,tidak ada hubungan,tidak ada hubungan,kedua kategori tersebut tidak berkaitan atau b...
4218,2015-B5_R25-3,2015,<blok> Pengalaman kerja </blok><pertanyaan> Al...,2020-klasifikas-1,2020,<blok> </blok><pertanyaan> Klasifikasi Desa/ ...,tidak ada hubungan,tidak ada hubungan,kedua kategori tersebut tidak berkaitan atau b...
4219,2017-b5_r1a-15,2017,<blok> Karakteristik umum </blok><pertanyaan> ...,2020-r31b-1,2020,<blok> Kegiatan lain </blok><pertanyaan> Dalam...,tidak ada hubungan,tidak ada hubungan,kedua kategori tersebut tidak berkaitan atau b...
4220,2015-B5_R1A-12,2015,<blok> Pendidikan </blok><pertanyaan> Apakah p...,2020-r19c-2,2020,<blok> </blok><pertanyaan> Apakah Anda melaku...,tidak ada hubungan,tidak ada hubungan,kedua kategori tersebut tidak berkaitan atau b...
4221,2012-B5P15E-1,2012,<blok> Pekerjaan utama </blok><pertanyaan> Apa...,2020-r4-2,2020,<blok> </blok><pertanyaan> Apakah status perk...,tidak ada hubungan,tidak ada hubungan,kedua kategori tersebut tidak berkaitan atau b...

In [ ]:
import pandas as pd

datasets = {
    "train_df": train_df,
    "valid_df": valid_df,
    "test_df":  test_df,
}

# Gabungkan semua value_counts menjadi satu tabel
counts_table = pd.concat(
    {name: df["relationship"].value_counts(dropna=False) for name, df in datasets.items()},
    axis=1
).fillna(0).astype(int)

# (opsional) urutkan baris label sesuai total terbanyak
counts_table = counts_table.loc[counts_table.sum(axis=1).sort_values(ascending=False).index]

# (opsional) tambah total per kolom
counts_table.loc["TOTAL"] = counts_table.sum(axis=0)

display(counts_table)          # Jupyter/Colab
# print(counts_table.to_string())  # kalau mau versi print juga

                    train_df  valid_df  test_df
relationship
tidak ada hubungan      2245       563     2808
equivalent              1529       383     1912
lebih khusus dari        359        89      448
lebih umum dari          359        89      448
TOTAL                   4492      1124     5616